services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: finance_admin
      POSTGRES_PASSWORD: senha_forte_123!
      POSTGRES_DB: finance_control
    ports:
      - '5433:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U finance_admin -d finance_control"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  backend:
    build: ./backend
    command: uvicorn app.interface.api.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      POSTGRES_USER: finance_admin
      POSTGRES_PASSWORD: senha_forte_123!
      POSTGRES_DB: finance_control
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      JWT_SECRET_KEY: your-super-secret-jwt-key-change-in-production
      JWT_ALGORITHM: HS256
      JWT_ACCESS_TOKEN_EXPIRE_MINUTES: 30
      JWT_REFRESH_TOKEN_EXPIRE_DAYS: 7
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "https://solidtechsolutions.com.br/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    build: 
      context: ./frontend
      target: development
    environment:
      REACT_APP_API_URL: https://solidtechsolutions.com.br/api
      NODE_ENV: development
    ports:
      - '3000:3000'
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  db_data:
    driver: local 